### ISSUE TITLE
Computation failed in stat_sina()

### ISSUE THREAD

**Issue by james-chuang** [thomasp85/ggforce#134]
There seems to be a bug with `geom_sina` in the latest release, which can also be seen in the documentation [here](https://cran.r-project.org/web/packages/ggforce/vignettes/Visual_Guide.html#sinaplot).

Minimal reprex:

``` r
library(ggforce)
#> Loading required package: ggplot2
ggplot(data = iris) +
    geom_sina(aes(x=Species, y=Sepal.Width))
#> Warning: Computation failed in `stat_sina()`:
#> Please use `to_lower_ascii()`, which works fine in all locales.
```

![](https://i.imgur.com/ImfoHvJ.png)

<sup>Created on 2019-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jpryda** [comment]
Am getting this too

**Comment by liuyanguu** [comment]
Thank you Thomas for the new ggforce! I ran into the same problem saying "Please use `to_lower_ascii()`", but it is solved then updated to ‘0.2.1.9000’. 
I got another warning which did not appear before, the reason of which is I have one variable that is all zero.
```
Computation failed in `stat_sina()`:
need at least two non-NA values to interpolate
```
So I have to remove that variable.

**Comment by erhoppe** [comment]
I'm still getting the issue.

```
> library(ggforce)
> ggplot(midwest, aes(state, area)) +
+   geom_sina()
Warning: Computation failed in `stat_sina()`:
Please use `to_lower_ascii()`, which works fine in all locales.
```
Here's my sessionInfo():
```
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggforce_0.2.1 ggplot2_3.1.1
```
I tried installing the dev version from github, but encountered this issue:
```
> library(ggforce)
Warning in get(method, envir = home) :
  internal error -3 in R_decompress1
Error: package or namespace load failed for ‘ggforce’ in get(method, envir = home):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ggforce/R/ggforce.rdb' is corrupt
```

Any ideas?

**Comment by erhoppe** [comment]
I just installed 0.2.0 and can confirm that this older version doesn't have a problem in my environment.

**Comment by liuyanguu** [comment]
@erhoppe you need to install version '‘0.2.1.9000’' from github: 
```
devtools::install_github("thomasp85/ggforce")
```

**Comment by pilopilota** [comment]
I 'solved' the issue by imposing 
`method = 'density'`
